CREATE TABLE IF NOT EXISTS `Z_MIGRATION` (
    `ID`            INT AUTO_INCREMENT PRIMARY KEY,
    `MIGRATION`     VARCHAR(255) NOT NULL,
    `CREATED_AT`    DATETIME NOT NULL,

    UNIQUE (`MIGRATION`)
);