CREATE TABLE IF NOT EXISTS `COLLECTION` (
    `ID`            INT AUTO_INCREMENT PRIMARY KEY,
    `ID_USER`       INT NOT NULL,
    `NAME`          VARCHAR(255) NOT NULL,
    `CREATED_AT`    DATETIME NOT NULL,
    `UPDATED_AT`    DATETIME NOT NULL,
    `SETTINGS`      JSON NOT NULL,

    UNIQUE (`ID_USER`, `NAME`),

    FOREIGN KEY (`ID_USER`) REFERENCES `USER`(`ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
);