CREATE TABLE IF NOT EXISTS `LESSON` (
    `ID`            INT AUTO_INCREMENT PRIMARY KEY,
    `ID_COLLECTION` INT NOT NULL,
    `ORDER`         INT NOT NULL,
    `NAME`          VARCHAR(255) NOT NULL,
    `DESCRIPTION`   VARCHAR(255) NOT NULL,
    `CREATED_AT`    DATETIME NOT NULL,
    `UPDATED_AT`    DATETIME NOT NULL,

    UNIQUE (`ID_COLLECTION`, `NAME`),

    FOREIGN KEY (`ID_COLLECTION`)   REFERENCES `COLLECTION`(`ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
);