const CardType = {
    FRENTE_E_VERSO: "FB",
    MULTIPLA_ESCOLHA: "MC",
    VERDADEIRO_OU_FALSO: "TF",
    RESPOSTA_POR_ESCRITO: "WA",
    PREENCHER_LACUNAS: "FI",
    ASSOCIAR_COLUNAS: "CA",
    ORDENAR_PARAGRAFOS: "OP"
}

module.exports = { CardType }