module.exports = {
    BCRYPT_SALT: 10,
    MAX_TOKEN_AGE_SECONDS: 24 * 60 * 60,
    DEFAULT_CARTOES_INICIAR_LICAO: 10,
    DEFAULT_QTDE_REPETICOES_APRENDENDO: 5,
    MAX_QTDE_REPETICOES_APRENDENDO: 10,
    MIN_ESPACAMENTO_APRENDENDO: 7200,
    DEFAULT_EASINESS_FACTOR: 2.0,
    MIN_EASINESS_FACTOR: 1.2
}